version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      # Add pip commands here if you have dependencies in requirements.txt
  build:
    commands:
      - echo "Build started on $(date)"
      - python hello_world.py
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - hello_world.py
